# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            YCC website
tagline:          'myCV'
description:      'test 123.'
url:              https://yinchengchen23.github.io/myCV
baseurl:          /myCV

author:
  name:           'Yincheng Chen'
  url:            https://github.com/YinchengChen23

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/YinchengChen23/myCV
